name: OpToggle
author: michaelmvv
version: 1
description: Toggle op stauts, Could be usefull on prison servers.
main: opToggle.Toggle
commands:
  opToggle:
    description: Toggles op status
    permission: optoggle.toggle
    permission-message: You don't have optoggle.toggle
  