name: OpToggle
author: michaelmvv
version: 1
description: Toggle Op status, has uses on prison servers.
main: opToggle.Toggle
commands:
  ToggleOP:
    description: Toggles Op status
    permission: optoggle.toggle
    permission-message: No Permission
  OpToggleUpdateCheck:
    description: Check for OpToggle Updates
    permission: optoggle.update
    permission-message: No Permission
  